name: Main

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended

      - name: Compile LaTeX to PDF
        run: |
          pdflatex flaky-tests.tex

      - name: Create or Update Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          name: "WhenShouldIFixFlakyTests"
          allowUpdates: true
          artifacts: |
            flaky-tests.pdf

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flaky-tests.pdf
          asset_name: flaky-tests.pdf
          asset_content_type: application/pdf
          token: ${{ secrets.GITHUB_TOKEN }}